### ISSUE TITLE
Barefoot switch compilation error 

### ISSUE THREAD

**Issue by HERMIT-OuO** [ATP-NSDI/ATP#1]
When I compiled p4ml.p4 in the Barefoot programmable switch, the following error occurred: 

`warning: Tofino does not support emitting constant 0 in digest, skipped /root/bf-sde-9.1.0/pkgsrc/p4-examples/p4_16_programs/p4ml/includes/actions.p4(13): [--Werror=target-error] error: noequ0_processentry1andWriteToPacket: Unsupported on target The table .noequ0_processEntry1andWriteToPacket with no key cannot have the action noequ0_processentry1andWriteToPacket.  This action requires hash, which can only be done through the hit pathway.  However, because the table has multiple actions, the driver may need to change at runtime, and the driver can only currently program the miss pathway.  The solution may be to declare only one action on the table, and mark it as the default action.`

My operating environment is: Barefoot SDE 9.1.0 

I have no clue about this. Hope to get your answer.

**Comment by yfle0707** [comment]
Hi,

The code is compiled with SDE 8.9.1. It also gets compiled with SDE 8.9.2. 

Could you please try with SDE 8.9.x?  

Thanks!
Yanfang

**Comment by HERMIT-OuO** [comment]
Thank you very much for your reply, I will give it a try!
