### ISSUE TITLE
How to get "Time to accuracy" figure?

### ISSUE THREAD

**Issue by frankmaster6** [ATP-NSDI/ATP#6]
I found in you project, you just 1) initialize a vector, 2) pull and push the vector for many times, 3) calculte the time. It seems there is no code attach to AI models. So I wonder how you got figure 11 in your NSDI paper.

**Comment by laochonlam** [comment]
Hi @frankmaster6, Thanks for your interest. We found that many people like you are interested in the integration of BytePS&ATP. I am going to release that these days.

Thanks,
Lam

**Comment by frankmaster6** [comment]
> Hi @frankmaster6, Thanks for your interest. We found that many people like you are interested in the integration of BytePS&ATP. I am going to release that these days.
> 
> Thanks, Lam

Thank you. I'm looking forward to your future release.

Thanks,
Frank

**Comment by laochonlam** [comment]
Hi @frankmaster6,

The source code for the training framework is released. Please check [here](https://github.com/in-ATP/ATP-BytePS)!

**Comment by frankmaster6** [comment]
> Hi @frankmaster6,
> 
> The source code for the training framework is released. Please check [here](https://github.com/in-ATP/ATP-BytePS)!

Great! Thanks for your new release.
