### ISSUE TITLE
ImportError: No module named pltfm_pm_rpc

### ISSUE THREAD

**Issue by 1908639561** [ATP-NSDI/ATP#7]
when I ran $SDE/run_p4_tests.sh -t ~/switchML/ptf/ -p switchml.

Target is asic-model
Setting up veth interfaces
No of Veths is 64
Adding CPU veth
Connecting to localhost port 7777 to check status on these devices: [0]
Waiting for device 0 to be ready
Started port clean script
WARNING: No route found for IPv6 destination :: (no default route?)
Traceback (most recent call last):
  File "/home/sde-test/bf-sde-8.9.1/install/bin/ptf", line 522, in <module>
    test_modules = load_test_modules(config)
  File "/home/sde-test/bf-sde-8.9.1/install/bin/ptf", line 413, in load_test_modules
    mod = imp.load_module(modname, *imp.find_module(modname, [root]))
  File "/home/sde-test/switchML/ptf/ptfTest.py", line 4, in <module>
    import pltfm_pm_rpc
ImportError: No module named pltfm_pm_rpc

I have no clue about this. Hope to get your answer.

**Comment by laochonlam** [comment]
Hi @1908639561 ,

I think your environment is not properly set. @yfle0707 Do you have clues about this?

Lam

**Comment by yfle0707** [comment]
Hi, @1908639561 , which SDE version you are using?

Also, could you please try commentating "import pltfm_pm_rpc"  and try if we actually need that module?

**Comment by 1908639561** [comment]
Hi,@laochonlam @yfle0707 .Thank you so much for receiving your response! 
I am using SDE-8.9.1. but I am not using a real P4 physical switch, I installed SDE-8.9.1 on a server with ubuntu-16.04 because I wanted to do it on Tofino Model first.
Also, when I run it after commenting out "import pltfm_pm_rpc", it has this problem:
![image](https://user-images.githubusercontent.com/95405577/176064013-70fd190e-c16e-4a75-99e4-870849214b5a.png)

**Comment by 1908639561** [comment]
When I commented out the sentences at the same time, it worked successfully.But I don't know why and what are the effects of doing so.
https://github.com/in-ATP/ATP/blob/ddca27f035edcd970abdbbfef400045d79afd3fa/ptf/ptfTest.py#L4
https://github.com/in-ATP/ATP/blob/ddca27f035edcd970abdbbfef400045d79afd3fa/ptf/ptfTest.py#L11
https://github.com/in-ATP/ATP/blob/ddca27f035edcd970abdbbfef400045d79afd3fa/ptf/ptfTest.py#L56
![image](https://user-images.githubusercontent.com/95405577/176076193-144655e6-8e75-41c9-8db7-6deafabbc237.png)

Output after successful run：
![image](https://user-images.githubusercontent.com/95405577/176076679-f138c2ba-832e-4125-8665-16347db0b4ea.png)



> Hi, @1908639561 , which SDE version you are using?
> 
> Also, could you please try commentating "import pltfm_pm_rpc" and try if we actually need that module?

**Comment by yfle0707** [comment]
Hi, 

The variable **self.platform_type** is not used, thus, it does not impact on the current program.

**Comment by 1908639561** [comment]
OK！Thank you very much for your replies!
