### ISSUE TITLE
Questions on ATP's P4 Source Code

### ISSUE THREAD

**Issue by qumalangma** [ATP-NSDI/ATP#9]
I hope this message finds you well. I am currently studying the ATP's P4 source code, and I would be very grateful if you could help me understand these questions.

Q1. In common.p4 at line 162, there is a function call bit_andcb(mdata.isAggregate, p4ml.bitmap, mdata.bitmap);. I am not familiar with bit_andcb, and I couldn't find a corresponding description for it in the P4_14 syntax. Could you explain what it does or direct me to relevant documentation?

Q2. In p4ml.p4 at line 93, I believe this branch of the conditional is for the last aggregation packet received. I am wondering why the packet does not need to be resubmitted here. Wouldn't this mean that the last 32 gradients are left unaggregated?

Q3. In p4ml.p4 at line 133, I think this branch is for the first aggregation packet received, where the gradient is stored in the register. Combined with Line 93, when there are three workers, three packets need to be aggregated. I'm wondering how is the second packet aggregated?

Q4. In the outPort_table, the packet received from the worker is forwarded to the loopback port. Does this mean that the packet will repeat the aggregation process? I find this part a bit confusing and would appreciate any clarification.

Thank you very much for your time and assistance. I greatly appreciate any guidance you could provide on these points.

Best regards

**Comment by laochonlam** [comment]
Hi @qumalangma,

Apologies for the delayed reply. Regarding your question about relevant documentation, you can find the materials from Intel's official website.

As for the other questions, we currently do not have the resources for ongoing maintenance. However, one approach to understanding the code is to use Intel's behavior model to run the code and analyze the logs, or to run it on the Tofino hardware to trace the behavior.

Thanks,
Lam

**Comment by qumalangma** [comment]
Thank you very much for your earlier work.

As I am not particularly familiar with the syntax of P4_14, I have analyzed the original code and adapted it by copying the existing implementation and adjusting parts of the code logic. Please note that some portions of the code differ from the presentation in the paper, with a focus on handling AGTR conflicts. The testing on the H3C switch has now been successfully completed.

If permitted, I would like to update the modified code in the repository.

**Comment by laochonlam** [comment]
Hi @qumalangma ,

Glad it could be of help to you. Additionally, I believe there is an experimental_p416 branch that contains the P4_16 code developed by another student afterward. I’m not sure if it is well-tested, but you might find it useful.

And sure— we absolutely welcome your contributions to the code!

**Comment by qumalangma** [comment]
I'm sorry for what I mentioned earlier: I had already conducted relevant tests on the program on the device. 
However, after retesting the code before submission, I found that the aggregation operation in the latter part of the resubmitted packet actually has an issue.
and I haven’t identified the cause yet. 
I’m struggling with it --- please look forward to my good news.

**Comment by laochonlam** [comment]
Thanks for the update - I’m sure you’ll resolve it soon!
